cc0 CC:
	{{CC}} -std=c++20 -S ../impl/strict/isd-0-getu.cpp
	{{CC}} -std=c++20 -c ../impl/strict/isd-0-getu.cpp
	{{CC}} -std=c++20 -S ../impl/strict/isd-u8-getu.cpp
	{{CC}} -std=c++20 -c ../impl/strict/isd-u8-getu.cpp
	{{CC}} -std=c++20 -S ../impl/strict/isd-sub-1-getu.cpp
	{{CC}} -std=c++20 -c ../impl/strict/isd-sub-1-getu.cpp
	{{CC}} -std=c++20 -S ../impl/strict/isd-sub-2-getu.cpp
	{{CC}} -std=c++20 -c ../impl/strict/isd-sub-2-getu.cpp
	{{CC}} -std=c++20 -S ../impl/strict/isd-range-1-getu.cpp
	{{CC}} -std=c++20 -c ../impl/strict/isd-range-1-getu.cpp
	{{CC}} -std=c++20 -S ../impl/strict/swar-16-getu.cpp
	{{CC}} -std=c++20 -c ../impl/strict/swar-16-getu.cpp
	{{CC}} -std=c++20 -S ../impl/strict/swar-16-1-getu.cpp
	{{CC}} -std=c++20 -c ../impl/strict/swar-16-1-getu.cpp
	{{CC}} -std=c++20 -S ../impl/strict/swar-32-getu.cpp
	{{CC}} -std=c++20 -c ../impl/strict/swar-32-getu.cpp
	{{CC}} -std=c++20 -S ../impl/strict/swar-64-getu.cpp
	{{CC}} -std=c++20 -c ../impl/strict/swar-64-getu.cpp
	{{CC}} -std=c++20 -S ../impl/strict/pre-16-getu.cpp
	{{CC}} -std=c++20 -c ../impl/strict/pre-16-getu.cpp

cc1 CC:
	{{CC}} -std=c++20 bench.cpp -falign-functions=256 -DBM_CASE=0x00 isd-0-getu.o
	./a.out
	{{CC}} -std=c++20 bench.cpp -falign-functions=256 -DBM_CASE=0x01 isd-u8-getu.o
	./a.out
	{{CC}} -std=c++20 bench.cpp -falign-functions=256 -DBM_CASE=0x02 isd-sub-1-getu.o
	./a.out
	{{CC}} -std=c++20 bench.cpp -falign-functions=256 -DBM_CASE=0x03 isd-sub-2-getu.o
	./a.out
	{{CC}} -std=c++20 bench.cpp -falign-functions=256 -DBM_CASE=0x04 isd-range-1-getu.o
	./a.out
	{{CC}} -std=c++20 bench.cpp -falign-functions=256 -DBM_CASE=0x05 swar-16-getu.o
	./a.out
	{{CC}} -std=c++20 bench.cpp -falign-functions=256 -DBM_CASE=0x06 swar-16-1-getu.o
	./a.out
	{{CC}} -std=c++20 bench.cpp -falign-functions=256 -DBM_CASE=0x07 swar-32-getu.o
	./a.out
	{{CC}} -std=c++20 bench.cpp -falign-functions=256 -DBM_CASE=0x08 swar-64-getu.o
	./a.out
	{{CC}} -std=c++20 bench.cpp -falign-functions=256 -DBM_CASE=0x09 pre-16-getu.o
	./a.out

bench-gcc-o2:
	just cc0 "g++ -O2 -g"
	just cc1 "g++ -O2"
	mv *.s *.o build/gcc-o2/

bench-gcc-o3:
	just cc0 "g++ -O3"
	just cc1 "g++ -O3"
	mv *.s *.o build/gcc-o3/

bench-clang-o2:
	just cc0 "clang++ -O2"
	just cc1 "clang++ -O2"
	mv *.s *.o build/clang-o2/

bench-clang-o3:
	just cc0 "clang++ -O3"
	just cc1 "clang++ -O3"
	mv *.s *.o build/clang-o3/

bench:
	just bench-gcc-o2 > build/gcc-o2/result.txt
	just bench-gcc-o3 > build/gcc-o3/result.txt
	just bench-clang-o2 > build/clang-o2/result.txt
	just bench-clang-o3 > build/clang-o3/result.txt

clean:
	rm *.asm *.o *.s a.out -f
	rm build/ -r
	mkdir build
	cd build && mkdir gcc-o2 gcc-o3 clang-o2 clang-o3
